"""fix base_class

Revision ID: 03609f09d4e9
Revises: 224174b26a4e
Create Date: 2020-11-07 21:19:09.366010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03609f09d4e9'
down_revision = '224174b26a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
