"""small fix Cancelation

Revision ID: 079deb98c762
Revises: 7bd50821881a
Create Date: 2020-12-29 14:42:28.124536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079deb98c762'
down_revision = '7bd50821881a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cancelation', 'payment_method')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancelation', sa.Column('payment_method', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Способ оплаты'))
    # ### end Alembic commands ###
