"""small fix Cancellation

Revision ID: 0b23ca6f81e3
Revises: 8e42984bcecc
Create Date: 2020-12-30 20:14:17.564888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b23ca6f81e3'
down_revision = '8e42984bcecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellation',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('shop_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('number', sa.String(length=255), nullable=True, comment='Номер'),
    sa.Column('date', sa.DateTime(), nullable=True, comment='Дата'),
    sa.Column('supplier', sa.String(length=255), nullable=True, comment='Поставщик'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='Примечание'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cancellationrecord',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('shop_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('cancellation_id', postgresql.UUID(as_uuid=True), nullable=False, comment='Списание'),
    sa.Column('rawremainsdetail_id', postgresql.UUID(as_uuid=True), nullable=False, comment='Id сырья в остатках'),
    sa.Column('quantity', sa.Float(), nullable=True, comment='Количество'),
    sa.ForeignKeyConstraint(['cancellation_id'], ['cancellation.id'], ),
    sa.ForeignKeyConstraint(['rawremainsdetail_id'], ['rawremainsdetail.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cancellationrecord')
    op.drop_table('cancellation')
    # ### end Alembic commands ###
