"""fix delete product from productrawrelation

Revision ID: 1dcf8d432c00
Revises: 03609f09d4e9
Create Date: 2020-11-08 21:06:12.386104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcf8d432c00'
down_revision = '03609f09d4e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('productrawrelation_product_id_fkey', 'productrawrelation', type_='foreignkey')
    op.create_foreign_key(None, 'productrawrelation', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productrawrelation', type_='foreignkey')
    op.create_foreign_key('productrawrelation_product_id_fkey', 'productrawrelation', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
