"""add price

Revision ID: 47a21db1cfa4
Revises: 25b8453aa45b
Create Date: 2021-03-28 10:41:17.238871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a21db1cfa4'
down_revision = '25b8453aa45b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordersproductsrelation', sa.Column('price', sa.Float(), nullable=False, comment='Цена'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordersproductsrelation', 'price')
    # ### end Alembic commands ###
