"""add permissions for user

Revision ID: 398ff67c80e3
Revises: fbe2dfb81e4e
Create Date: 2021-04-13 13:23:46.845582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '398ff67c80e3'
down_revision = 'fbe2dfb81e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('orders', sa.String(length=255), nullable=True, comment='Права на работу с заказами'),
    sa.Column('products', sa.String(length=255), nullable=True, comment='Права на работу с продуктами'),
    sa.Column('raw', sa.String(length=255), nullable=True, comment='Права на работу с сырьем'),
    sa.Column('clients', sa.String(length=255), nullable=True, comment='Права на работу с клиентами'),
    sa.Column('staff', sa.String(length=255), nullable=True, comment='Права на работу с персоналом'),
    sa.Column('warehouse', sa.String(length=255), nullable=True, comment='Права на работу со складом'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    # ### end Alembic commands ###
