"""fix name of inventoty records

Revision ID: ca315884d9cc
Revises: 62dc73ebcc8d
Create Date: 2021-04-29 15:12:22.053803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca315884d9cc'
down_revision = '62dc73ebcc8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
