"""add piece id for raw

Revision ID: 602d6c1f182b
Revises: 1db02dfb1a1b
Create Date: 2021-05-06 17:44:39.700965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '602d6c1f182b'
down_revision = '1db02dfb1a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw', sa.Column('piece_raw_id', postgresql.UUID(as_uuid=True), nullable=True, comment='Id разборного сырья'))
    op.add_column('raw', sa.Column('piece_unit', sa.String(length=255), nullable=True, comment='Ед. измерения разборного сырья'))
    op.create_foreign_key(None, 'raw', 'raw', ['piece_raw_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw', type_='foreignkey')
    op.drop_column('raw', 'piece_unit')
    op.drop_column('raw', 'piece_raw_id')
    # ### end Alembic commands ###
