"""order number as primary key

Revision ID: c45f4067929c
Revises: 47fe79db2938
Create Date: 2021-03-31 10:22:38.181641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45f4067929c'
down_revision = '47fe79db2938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
