"""add product set model

Revision ID: 19227b5eef50
Revises: 5d6957dc9ce5
Create Date: 2021-06-22 14:26:39.031389

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19227b5eef50'
down_revision = '5d6957dc9ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_set',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('shop_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Описание'),
    sa.Column('image', sa.String(length=255), nullable=True, comment='Изображение'),
    sa.Column('price', sa.Float(), nullable=True, comment='Цена'),
    sa.Column('old_price', sa.Float(), nullable=True, comment='Старая цена'),
    sa.Column('show_on_store', sa.Boolean(), nullable=False, comment='Отображать на витрине'),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_set_relation',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('product_set_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['product_set_id'], ['product_set.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_set_relation')
    op.drop_table('product_set')
    # ### end Alembic commands ###
