"""add remark for remains detail

Revision ID: 62dc73ebcc8d
Revises: 81f093fc257c
Create Date: 2021-04-29 14:51:53.415284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62dc73ebcc8d'
down_revision = '81f093fc257c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rawremainsdetail', sa.Column('remark', sa.String(length=255), nullable=True, comment='Примечание'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rawremainsdetail', 'remark')
    # ### end Alembic commands ###
