"""add client to order1

Revision ID: 47fe79db2938
Revises: 08839d3f5665
Create Date: 2021-03-30 22:22:04.123485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fe79db2938'
down_revision = '08839d3f5665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
