"""order number as squence1

Revision ID: 5ee9db7cd0ae
Revises: 4b3f3e5e622b
Create Date: 2021-04-01 12:42:11.678992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence


# revision identifiers, used by Alembic.
revision = '5ee9db7cd0ae'
down_revision = '4b3f3e5e622b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(DropSequence(Sequence('number_seq')))
    op.execute(CreateSequence(Sequence('number_seq', minvalue=100000, maxvalue=999999, cycle=True, increment=1)))
    op.add_column('orders', sa.Column('order_number', sa.Integer(), server_default=sa.text("nextval('number_seq')"), nullable=False, comment='№ заказа'))
    op.drop_column('orders', 'number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False, comment='№ заказа'))
    op.drop_column('orders', 'order_number')
    # ### end Alembic commands ###
