"""add client to order

Revision ID: 08839d3f5665
Revises: 24c56e2a9c9f
Create Date: 2021-03-30 21:59:15.646474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08839d3f5665'
down_revision = '24c56e2a9c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
