"""product set

Revision ID: cbaa58419960
Revises: 5d6957dc9ce5
Create Date: 2021-06-23 15:45:50.343675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cbaa58419960'
down_revision = '5d6957dc9ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('base', sa.Boolean(), nullable=False, comment='Базовый товар'))
    op.add_column('product', sa.Column('product_set_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_product_product_set_id'), 'product', ['product_set_id'], unique=True)
    op.create_table('product_set_relation',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('product_set_id', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('quantity', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
                    sa.ForeignKeyConstraint(['product_set_id'], ['product.product_set_id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_set_relation')
    op.drop_index(op.f('ix_product_product_set_id'), table_name='product')
    op.drop_column('product', 'product_set_id')
    op.drop_column('product', 'base')
    # ### end Alembic commands ###
