"""fix client - address relationship

Revision ID: d79b389ba070
Revises: 47a21db1cfa4
Create Date: 2021-03-29 22:44:44.007375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd79b389ba070'
down_revision = '47a21db1cfa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('address_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('client_address_fkey', 'client', type_='foreignkey')
    op.create_foreign_key(None, 'client', 'address', ['address_id'], ['id'])
    op.drop_column('client', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('address', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.create_foreign_key('client_address_fkey', 'client', 'address', ['address'], ['id'])
    op.drop_column('client', 'address_id')
    # ### end Alembic commands ###
