"""order number as squence

Revision ID: 4b3f3e5e622b
Revises: 47fe79db2938
Create Date: 2021-04-01 11:31:59.803149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.schema import Sequence, CreateSequence

revision = '4b3f3e5e622b'
down_revision = '47fe79db2938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('number', sa.Integer(), nullable=False, comment='№ заказа'))
    op.execute(CreateSequence(Sequence('number_seq', minvalue=100000, cycle=True, increment=1)))
    op.drop_constraint('orders_order_number_key', 'orders', type_='unique')
    op.drop_column('orders', 'order_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_number', sa.INTEGER(), autoincrement=False, nullable=False, comment='№ заказа'))
    op.create_unique_constraint('orders_order_number_key', 'orders', ['order_number'])
    op.drop_column('orders', 'number')
    # ### end Alembic commands ###
