"""add name and image fields

Revision ID: fbe2dfb81e4e
Revises: 5ee9db7cd0ae
Create Date: 2021-04-12 11:27:40.774692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe2dfb81e4e'
down_revision = '5ee9db7cd0ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordersproductsrelation', sa.Column('image', sa.String(length=255), nullable=True, comment='Изображение'))
    op.add_column('ordersproductsrelation', sa.Column('name', sa.String(length=255), nullable=True, comment='Название'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordersproductsrelation', 'name')
    op.drop_column('ordersproductsrelation', 'image')
    # ### end Alembic commands ###
