"""add old quantity

Revision ID: d84501ae016d
Revises: 398ff67c80e3
Create Date: 2021-04-13 17:18:31.002663

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd84501ae016d'
down_revision = '398ff67c80e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventoryrecord', sa.Column('old_quantity', sa.Float(), nullable=True, comment='Остаток по программе'))
    op.alter_column('inventoryrecord', 'quantity',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment='Остаток по факту инвентаризации',
               existing_comment='Количество',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inventoryrecord', 'quantity',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment='Количество',
               existing_comment='Остаток по факту инвентаризации',
               existing_nullable=True)
    op.drop_column('inventoryrecord', 'old_quantity')
    # ### end Alembic commands ###
