"""add piece id for raw1

Revision ID: f465a3c36ee7
Revises: 602d6c1f182b
Create Date: 2021-05-06 20:39:42.576879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f465a3c36ee7'
down_revision = '602d6c1f182b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('raw_piece_raw_id_fkey', 'raw', type_='foreignkey')
    op.create_foreign_key(None, 'raw', 'raw', ['piece_raw_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw', type_='foreignkey')
    op.create_foreign_key('raw_piece_raw_id_fkey', 'raw', 'raw', ['piece_raw_id'], ['id'])
    # ### end Alembic commands ###
