"""update raw model

Revision ID: e0f5fcd802b6
Revises: 5adeb7569310
Create Date: 2021-04-25 20:38:30.747687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f5fcd802b6'
down_revision = '5adeb7569310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw', sa.Column('article_number', sa.String(length=255), nullable=True, comment='Артикул'))
    op.add_column('raw', sa.Column('helium_consumption', sa.Float(), nullable=True, comment='Расход гелия'))
    op.add_column('raw', sa.Column('manufacturer', sa.String(length=255), nullable=True, comment='Производитель'))
    op.add_column('raw', sa.Column('red_label', sa.Float(), nullable=True, comment='Красная метка'))
    op.add_column('raw', sa.Column('yellow_label', sa.Float(), nullable=True, comment='Желтая метка'))
    op.alter_column('raw', 'per_pack',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_comment='В упаковке',
               existing_nullable=True)
    op.drop_column('raw', 'yellow_signal')
    op.drop_column('raw', 'red_signal')
    op.drop_column('raw', 'green_signal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw', sa.Column('green_signal', sa.INTEGER(), autoincrement=False, nullable=True, comment='Зеленая метка'))
    op.add_column('raw', sa.Column('red_signal', sa.INTEGER(), autoincrement=False, nullable=True, comment='Красная метка'))
    op.add_column('raw', sa.Column('yellow_signal', sa.INTEGER(), autoincrement=False, nullable=True, comment='Желтая метка'))
    op.alter_column('raw', 'per_pack',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_comment='В упаковке',
               existing_nullable=True)
    op.drop_column('raw', 'yellow_label')
    op.drop_column('raw', 'red_label')
    op.drop_column('raw', 'manufacturer')
    op.drop_column('raw', 'helium_consumption')
    op.drop_column('raw', 'article_number')
    # ### end Alembic commands ###
