"""fix name of inventoty records

Revision ID: 9abf286a1b50
Revises: ca315884d9cc
Create Date: 2021-04-29 15:13:01.022417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abf286a1b50'
down_revision = 'ca315884d9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
