"""fix cancelation model

Revision ID: 4516cf2a7898
Revises: 640292ea3420
Create Date: 2021-04-30 13:26:55.541750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence, DropSequence


# revision identifiers, used by Alembic.
revision = '4516cf2a7898'
down_revision = '640292ea3420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cancellation', sa.Column('reason', sa.String(length=255), nullable=True, comment='Причина'))
    op.drop_column('cancellation', 'number')
    op.execute(CreateSequence(Sequence('cancel_number_seq', cycle=True, increment=1)))
    op.add_column('cancellation', sa.Column('number', sa.Integer(), server_default=sa.text("nextval('cancel_number_seq')"),
                                            nullable=False, comment='Номер'))
    op.drop_column('cancellation', 'supplier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(DropSequence(Sequence('cancel_number_seq', cycle=True, increment=1)))
    op.drop_column('cancellation', 'number')
    op.add_column('cancellation', sa.Column('supplier', sa.VARCHAR(length=255), autoincrement=False,
                                            nullable=True, comment='Поставщик'))
    op.add_column('cancellation', 'number',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Номер')
    op.drop_column('cancellation', 'reason')
    # ### end Alembic commands ###
