"""add quantity for raw model

Revision ID: 81f093fc257c
Revises: e0f5fcd802b6
Create Date: 2021-04-28 14:36:07.052975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f093fc257c'
down_revision = 'e0f5fcd802b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw', sa.Column('available_quantity', sa.Float(), nullable=True, comment='Остаток с учетом зарезервированного количества'))
    op.add_column('raw', sa.Column('quantity', sa.Float(), nullable=True, comment='Текущий остаток на складе'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw', 'quantity')
    op.drop_column('raw', 'available_quantity')
    # ### end Alembic commands ###
