"""add product set model 1

Revision ID: 7600cf16349d
Revises: 19227b5eef50
Create Date: 2021-06-22 16:30:46.285606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7600cf16349d'
down_revision = '19227b5eef50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
