"""fix client address relationship

Revision ID: 24c56e2a9c9f
Revises: d79b389ba070
Create Date: 2021-03-30 14:56:12.863618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24c56e2a9c9f'
down_revision = 'd79b389ba070'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('client_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'address', 'client', ['client_id'], ['id'])
    op.drop_constraint('client_address_id_fkey', 'client', type_='foreignkey')
    op.drop_column('client', 'address_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('address_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('client_address_id_fkey', 'client', 'address', ['address_id'], ['id'])
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'client_id')
    # ### end Alembic commands ###
