"""update raw model

Revision ID: 21cb1156e4f2
Revises: 1dcf8d432c00
Create Date: 2020-11-11 16:58:31.623965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21cb1156e4f2'
down_revision = '1dcf8d432c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_product_user_raw_uc', 'file', ['product_id', 'user_id', 'raw_id'])
    op.drop_constraint('_product_user_uc', 'file', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_product_user_uc', 'file', ['product_id', 'user_id'])
    op.drop_constraint('_product_user_raw_uc', 'file', type_='unique')
    # ### end Alembic commands ###
