"""fix raw model

Revision ID: 224174b26a4e
Revises: f49ea83cc95f
Create Date: 2020-11-06 17:44:44.514641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224174b26a4e'
down_revision = 'f49ea83cc95f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
