"""fix orders model

Revision ID: 279eb6b3ba92
Revises: 364473a1ded9
Create Date: 2020-12-25 11:58:43.479482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '279eb6b3ba92'
down_revision = '364473a1ded9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_number', sa.Integer(), autoincrement=True, nullable=False, comment='№ заказа'))
    op.alter_column('orders', 'courier_id',
               existing_type=postgresql.UUID(),
               comment='Курьер',
               existing_nullable=True)
    op.alter_column('orders', 'created_by_id',
               existing_type=postgresql.UUID(),
               comment='Принял',
               existing_nullable=True)
    op.alter_column('orders', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата поступления',
               existing_nullable=True)
    op.alter_column('orders', 'date_of_order',
               existing_type=postgresql.TIMESTAMP(),
               comment='Дата заказа',
               existing_nullable=False)
    op.alter_column('orders', 'make_by_id',
               existing_type=postgresql.UUID(),
               comment='Выполнил',
               existing_nullable=True)
    op.create_unique_constraint(None, 'orders', ['order_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.alter_column('orders', 'make_by_id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='Выполнил',
               existing_nullable=True)
    op.alter_column('orders', 'date_of_order',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата заказа',
               existing_nullable=False)
    op.alter_column('orders', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Дата поступления',
               existing_nullable=True)
    op.alter_column('orders', 'created_by_id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='Принял',
               existing_nullable=True)
    op.alter_column('orders', 'courier_id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='Курьер',
               existing_nullable=True)
    op.drop_column('orders', 'order_number')
    # ### end Alembic commands ###
