"""fix Raw model

Revision ID: 27ba8ed5b892
Revises: 20e215e5b27e
Create Date: 2020-12-09 10:07:16.030776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ba8ed5b892'
down_revision = '20e215e5b27e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
