"""fix invoice record model

Revision ID: 364473a1ded9
Revises: 293f46696f0e
Create Date: 2020-12-24 16:27:12.467386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364473a1ded9'
down_revision = '293f46696f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
