"""fix raw table v2

Revision ID: 38c51c88a9d7
Revises: e5df92585580
Create Date: 2020-11-03 15:33:55.419987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c51c88a9d7'
down_revision = 'e5df92585580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
