"""ProductRawRelation delete primary key

Revision ID: 3ce4cf94dbee
Revises: 49626294ea4d
Create Date: 2020-11-17 21:01:53.476008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce4cf94dbee'
down_revision = '49626294ea4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
