"""fix model productcategory and product

Revision ID: 4246e87cb551
Revises: 27a7e32978e0
Create Date: 2020-10-27 19:29:25.591261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4246e87cb551'
down_revision = '27a7e32978e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
