"""small fix model Raw

Revision ID: 53874a3375f5
Revises: 38c51c88a9d7
Create Date: 2020-11-03 21:02:22.796113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53874a3375f5'
down_revision = '38c51c88a9d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('productrawrelation_product_id_fkey', 'productrawrelation', type_='foreignkey')
    op.drop_constraint('productrawrelation_raw_id_fkey', 'productrawrelation', type_='foreignkey')
    op.create_foreign_key(None, 'productrawrelation', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'productrawrelation', 'raw', ['raw_id'], ['id'], ondelete='CASCADE')
    op.add_column('raw', sa.Column('unit', sa.String(length=255), nullable=True))
    op.drop_constraint('raw_category_id_fkey', 'raw', type_='foreignkey')
    op.create_foreign_key(None, 'raw', 'rawcategory', ['category_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw', type_='foreignkey')
    op.create_foreign_key('raw_category_id_fkey', 'raw', 'rawcategory', ['category_id'], ['id'])
    op.drop_column('raw', 'unit')
    op.drop_constraint(None, 'productrawrelation', type_='foreignkey')
    op.drop_constraint(None, 'productrawrelation', type_='foreignkey')
    op.create_foreign_key('productrawrelation_raw_id_fkey', 'productrawrelation', 'raw', ['raw_id'], ['id'])
    op.create_foreign_key('productrawrelation_product_id_fkey', 'productrawrelation', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
