"""image/images

Revision ID: 5bc290afad25
Revises: 6c112ceccdbb
Create Date: 2020-11-16 16:20:43.600835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bc290afad25'
down_revision = '6c112ceccdbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw', sa.Column('images', sa.String(length=255), nullable=True))
    op.drop_column('raw', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('raw', 'images')
    # ### end Alembic commands ###
