"""add row column to invoice record

Revision ID: 6849bcff73f2
Revises: 8d22211864cb
Create Date: 2020-12-06 14:35:34.942335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6849bcff73f2'
down_revision = '8d22211864cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoicerecord', 'raw_id',
               existing_type=postgresql.UUID(),
               comment='Id сырья',
               existing_comment='Название',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoicerecord', 'raw_id',
               existing_type=postgresql.UUID(),
               comment='Название',
               existing_comment='Id сырья',
               existing_nullable=False)
    # ### end Alembic commands ###
