"""remove files table

Revision ID: 6c112ceccdbb
Revises: 21cb1156e4f2
Create Date: 2020-11-13 14:02:28.601704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c112ceccdbb'
down_revision = '21cb1156e4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file')
    op.add_column('product', sa.Column('images', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('raw', sa.Column('image', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar')
    op.drop_column('raw', 'image')
    op.drop_column('product', 'images')
    op.create_table('file',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('product_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('raw_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='file_product_id_fkey'),
    sa.ForeignKeyConstraint(['raw_id'], ['raw.id'], name='file_raw_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='file_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='file_pkey'),
    sa.UniqueConstraint('path', name='file_path_key'),
    sa.UniqueConstraint('product_id', 'user_id', 'raw_id', name='_product_user_raw_uc')
    )
    # ### end Alembic commands ###
