"""remove default old price

Revision ID: 7174ff09169d
Revises: d08648e4bf7b
Create Date: 2020-12-20 13:53:18.803650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7174ff09169d'
down_revision = 'd08648e4bf7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
