"""add client address

Revision ID: 799d1e0a217d
Revises: fa04744d1c5b
Create Date: 2021-03-23 21:25:40.839488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '799d1e0a217d'
down_revision = 'fa04744d1c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=True, comment='Улица/мкрн'),
    sa.Column('house', sa.String(length=255), nullable=True, comment='Дом'),
    sa.Column('entrance', sa.String(length=255), nullable=True, comment='Подъезд'),
    sa.Column('floor', sa.String(length=255), nullable=True, comment='Этаж'),
    sa.Column('flat', sa.String(length=255), nullable=True, comment='Кв/офис'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('client', sa.Column('address', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'client', 'address', ['address'], ['id'])
    op.drop_column('client', 'entrance')
    op.drop_column('client', 'street')
    op.drop_column('client', 'floor')
    op.drop_column('client', 'flat')
    op.drop_column('client', 'house')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('house', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Дом'))
    op.add_column('client', sa.Column('flat', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Кв/офис'))
    op.add_column('client', sa.Column('floor', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Этаж'))
    op.add_column('client', sa.Column('street', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Улица/мкрн'))
    op.add_column('client', sa.Column('entrance', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Подъезд'))
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'address')
    op.drop_table('address')
    # ### end Alembic commands ###
