"""fix RawCategory

Revision ID: 8cfb7cc95fe9
Revises: 080b5c3bf420
Create Date: 2020-11-26 17:50:31.964446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cfb7cc95fe9'
down_revision = '080b5c3bf420'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'rawcategory', 'rawcategory', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rawcategory', type_='foreignkey')
    # ### end Alembic commands ###
