"""add model Inventory and InventoryRecord

Revision ID: 8d22211864cb
Revises: fe0adf41a254
Create Date: 2020-11-30 20:06:59.387607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d22211864cb'
down_revision = 'fe0adf41a254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('shop_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True, comment='Ответственный сотрудник'),
    sa.Column('number', sa.String(length=255), nullable=True, comment='Номер'),
    sa.Column('date', sa.DateTime(), nullable=True, comment='Дата'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='Примечание'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventoryrecord',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('shop_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('inventory_id', postgresql.UUID(as_uuid=True), nullable=False, comment='ИНВ Опись'),
    sa.Column('raw_id', postgresql.UUID(as_uuid=True), nullable=False, comment='Название'),
    sa.Column('quantity', sa.Float(), nullable=True, comment='Количество'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['raw_id'], ['raw.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventoryrecord')
    op.drop_table('inventory')
    # ### end Alembic commands ###
