"""fix raw model

Revision ID: 8e42984bcecc
Revises: 079deb98c762
Create Date: 2020-12-29 14:54:49.466979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8e42984bcecc'
down_revision = '079deb98c762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw', sa.Column('reserved', sa.Float(), nullable=True, comment='Зарезервировано'))
    op.drop_column('rawremainsdetail', 'reserved')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rawremainsdetail', sa.Column('reserved', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Зарезервировано'))
    op.drop_column('raw', 'reserved')
    # ### end Alembic commands ###
