"""fix orders model

Revision ID: 91d256f2682e
Revises: 6814201f0bfa
Create Date: 2020-12-25 14:30:35.701618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91d256f2682e'
down_revision = '6814201f0bfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
