"""fix order product raw relation model

Revision ID: 94e4759ec8e5
Revises: 91d256f2682e
Create Date: 2020-12-26 13:54:11.657374

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '94e4759ec8e5'
down_revision = '91d256f2682e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordersproductsrawrelation',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order_product_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('raw_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('standard_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_product_id'], ['ordersproductsrelation.id'], ),
    sa.ForeignKeyConstraint(['raw_id'], ['raw.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['rawusagestandards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ordersrawrelation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordersrawrelation',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('order_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('product_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('raw_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('standard_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='ordersrawrelation_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='ordersrawrelation_product_id_fkey'),
    sa.ForeignKeyConstraint(['raw_id'], ['raw.id'], name='ordersrawrelation_raw_id_fkey'),
    sa.ForeignKeyConstraint(['standard_id'], ['rawusagestandards.id'], name='ordersrawrelation_standard_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ordersrawrelation_pkey')
    )
    op.drop_table('ordersproductsrawrelation')
    # ### end Alembic commands ###
