"""small fix RawRemainsDetail, Invoice, InvoiceRecord tables

Revision ID: 994a10aa99a5
Revises: 8cfb7cc95fe9
Create Date: 2020-11-27 17:51:10.204949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '994a10aa99a5'
down_revision = '8cfb7cc95fe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('shop_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'invoice', 'shop', ['shop_id'], ['id'])
    op.add_column('invoicerecord', sa.Column('shop_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'invoicerecord', 'shop', ['shop_id'], ['id'])
    op.add_column('rawremainsdetail', sa.Column('shop_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'rawremainsdetail', 'shop', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rawremainsdetail', type_='foreignkey')
    op.drop_column('rawremainsdetail', 'shop_id')
    op.drop_constraint(None, 'invoicerecord', type_='foreignkey')
    op.drop_column('invoicerecord', 'shop_id')
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_column('invoice', 'shop_id')
    # ### end Alembic commands ###
