"""add shop_id in RawUsageStandards

Revision ID: ad2b2ec97a42
Revises: 27ba8ed5b892
Create Date: 2020-12-11 19:52:40.975760

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad2b2ec97a42'
down_revision = '27ba8ed5b892'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rawusagestandards', sa.Column('shop_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'rawusagestandards', 'shop', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rawusagestandards', type_='foreignkey')
    op.drop_column('rawusagestandards', 'shop_id')
    # ### end Alembic commands ###
