"""del relationship to shops in User model

Revision ID: b2e0ca2c9f22
Revises: 86f28ad5fa35
Create Date: 2020-08-16 17:57:52.350527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2e0ca2c9f22'
down_revision = '86f28ad5fa35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
