"""add parent_id

Revision ID: b61eba138800
Revises: 3ce4cf94dbee
Create Date: 2020-11-25 16:47:09.803782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b61eba138800'
down_revision = '3ce4cf94dbee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw', 'category_id',
               existing_type=postgresql.UUID(),
               comment='Категория',
               existing_nullable=False)
    op.add_column('rawcategory', sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True, comment='Id родительской категории'))
    op.alter_column('rawcategory', 'description',
               existing_type=sa.VARCHAR(length=255),
               comment='Описание',
               existing_nullable=True)
    op.alter_column('rawcategory', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Название категории',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rawcategory', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Название категории',
               existing_nullable=True)
    op.alter_column('rawcategory', 'description',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Описание',
               existing_nullable=True)
    op.drop_column('rawcategory', 'parent_id')
    op.alter_column('raw', 'category_id',
               existing_type=postgresql.UUID(),
               comment=None,
               existing_comment='Категория',
               existing_nullable=False)
    # ### end Alembic commands ###
