"""add comments to user model

Revision ID: b63b759dd8e9
Revises: fdbef9b5796c
Create Date: 2020-10-22 16:28:29.355567

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b63b759dd8e9'
down_revision = 'fdbef9b5796c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               comment='ФИО',
               existing_nullable=True)
    op.alter_column('user', 'is_staff',
               existing_type=sa.BOOLEAN(),
               comment='Владелец магазина',
               existing_nullable=False)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               comment='Права суперпользователя',
               existing_nullable=False)
    op.alter_column('user', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               comment='Последний вход',
               existing_nullable=True)
    op.alter_column('user', 'login',
               existing_type=sa.VARCHAR(length=255),
               comment='Логин',
               existing_nullable=False)
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               comment='Пароль',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Пароль',
               existing_nullable=True)
    op.alter_column('user', 'login',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Логин',
               existing_nullable=False)
    op.alter_column('user', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Последний вход',
               existing_nullable=True)
    op.alter_column('user', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Права суперпользователя',
               existing_nullable=False)
    op.alter_column('user', 'is_staff',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Владелец магазина',
               existing_nullable=False)
    op.alter_column('user', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='ФИО',
               existing_nullable=True)
    # ### end Alembic commands ###
