"""update database4

Revision ID: c72a2e169608
Revises: 733de03f46b8
Create Date: 2020-08-26 16:03:55.104665

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c72a2e169608'
down_revision = '733de03f46b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'path',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('file', 'product_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('product', 'category_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product', 'shop_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_constraint('product_name_key', 'product', type_='unique')
    op.add_column('productcategory', sa.Column('show_on_store', sa.Boolean(), nullable=False))
    op.drop_constraint('productcategory_name_key', 'productcategory', type_='unique')
    op.alter_column('shop', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('shop_name_key', 'shop', type_='unique')
    op.drop_constraint('user_login_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_login_key', 'user', ['login'])
    op.create_unique_constraint('shop_name_key', 'shop', ['name'])
    op.alter_column('shop', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint('productcategory_name_key', 'productcategory', ['name'])
    op.drop_column('productcategory', 'show_on_store')
    op.create_unique_constraint('product_name_key', 'product', ['name'])
    op.alter_column('product', 'shop_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('product', 'category_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('file', 'product_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('file', 'path',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
