""" add comments to product model

Revision ID: d08648e4bf7b
Revises: ad2b2ec97a42
Create Date: 2020-12-20 12:51:18.047652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd08648e4bf7b'
down_revision = 'ad2b2ec97a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(length=255),
               comment='Описание',
               existing_nullable=True)
    op.alter_column('product', 'image',
               existing_type=sa.VARCHAR(length=255),
               comment='Изображение',
               existing_nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment='Название',
               existing_nullable=False)
    op.alter_column('product', 'old_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment='Старая цена',
               existing_nullable=True)
    op.alter_column('product', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment='Цена',
               existing_nullable=True)
    op.alter_column('product', 'show_on_store',
               existing_type=sa.BOOLEAN(),
               comment='Отображать на витрине',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'show_on_store',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Отображать на витрине',
               existing_nullable=False)
    op.alter_column('product', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Цена',
               existing_nullable=True)
    op.alter_column('product', 'old_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Старая цена',
               existing_nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Название',
               existing_nullable=False)
    op.alter_column('product', 'image',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Изображение',
               existing_nullable=True)
    op.alter_column('product', 'description',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Описание',
               existing_nullable=True)
    # ### end Alembic commands ###
