"""fix order and client model

Revision ID: dcd7500c9090
Revises: 0b23ca6f81e3
Create Date: 2020-12-31 17:29:53.900762

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dcd7500c9090'
down_revision = '0b23ca6f81e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cancelationrecord')
    op.drop_table('cancelation')
    op.add_column('client', sa.Column('age', sa.Integer(), nullable=True, comment='Возраст'))
    op.add_column('client', sa.Column('discount_card', sa.String(length=255), nullable=True, comment='Дисконтная карта'))
    op.add_column('client', sa.Column('entrance', sa.String(length=255), nullable=True, comment='Подъезд'))
    op.add_column('client', sa.Column('flat', sa.String(length=255), nullable=True, comment='Кв/офис'))
    op.add_column('client', sa.Column('floor', sa.String(length=255), nullable=True, comment='Этаж'))
    op.add_column('client', sa.Column('house', sa.String(length=255), nullable=True, comment='Дом'))
    op.add_column('client', sa.Column('sex', sa.String(length=255), nullable=True, comment='Пол'))
    op.add_column('client', sa.Column('street', sa.String(length=255), nullable=True, comment='Улица/мкрн'))
    op.alter_column('client', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Имя')
    op.drop_column('client', 'address')
    op.drop_column('client', 'discount')
    op.add_column('orders', sa.Column('decoration_cost', sa.Float(), nullable=True, comment='Стоимость монтажа'))
    op.add_column('orders', sa.Column('delivery_cost', sa.Float(), nullable=True, comment='Стоимость доставки'))
    op.add_column('orders', sa.Column('discount_card', sa.String(length=255), nullable=True, comment='Дисконтная карта'))
    op.add_column('orders', sa.Column('promo', sa.String(length=255), nullable=True, comment='Промокод'))
    op.add_column('orders', sa.Column('reason', sa.String(length=255), nullable=True, comment='Повод для заказа'))
    op.add_column('orders', sa.Column('sales_channel', sa.String(length=255), nullable=True, comment='Канал продаж'))
    op.drop_constraint('ordersproductsrawrelation_raw_remains_id_fkey', 'ordersproductsrawrelation', type_='foreignkey')
    op.drop_column('ordersproductsrawrelation', 'raw_remains_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordersproductsrawrelation', sa.Column('raw_remains_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('ordersproductsrawrelation_raw_remains_id_fkey', 'ordersproductsrawrelation', 'rawremainsdetail', ['raw_remains_id'], ['id'])
    op.drop_column('orders', 'sales_channel')
    op.drop_column('orders', 'reason')
    op.drop_column('orders', 'promo')
    op.drop_column('orders', 'discount_card')
    op.drop_column('orders', 'delivery_cost')
    op.drop_column('orders', 'decoration_cost')
    op.add_column('client', sa.Column('discount', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Дисконтная карта'))
    op.add_column('client', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Адрес'))
    op.alter_column('client', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='Имя')
    op.drop_column('client', 'street')
    op.drop_column('client', 'sex')
    op.drop_column('client', 'house')
    op.drop_column('client', 'floor')
    op.drop_column('client', 'flat')
    op.drop_column('client', 'entrance')
    op.drop_column('client', 'discount_card')
    op.drop_column('client', 'age')
    op.create_table('cancelation',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('shop_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('number', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Номер'),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True, comment='Дата'),
    sa.Column('supplier', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Поставщик'),
    sa.Column('remark', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Примечание'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name='cancelation_shop_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cancelation_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('cancelationrecord',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('shop_id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('cancelation_id', postgresql.UUID(), autoincrement=False, nullable=False, comment='Списание'),
    sa.Column('rawremainsdetail_id', postgresql.UUID(), autoincrement=False, nullable=False, comment='Id сырья в остатках'),
    sa.Column('quantity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Количество'),
    sa.ForeignKeyConstraint(['cancelation_id'], ['cancelation.id'], name='cancelationrecord_cancelation_id_fkey'),
    sa.ForeignKeyConstraint(['rawremainsdetail_id'], ['rawremainsdetail.id'], name='cancelationrecord_rawremainsdetail_id_fkey'),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name='cancelationrecord_shop_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='cancelationrecord_pkey')
    )
    # ### end Alembic commands ###
