"""remove default raw_category parent_id

Revision ID: dd9220f74ea1
Revises: 6849bcff73f2
Create Date: 2020-12-06 14:45:32.923806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9220f74ea1'
down_revision = '6849bcff73f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
