"""update database

Revision ID: de03bfd82a47
Revises: 05b8081b7bf0
Create Date: 2020-08-26 13:42:39.779894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de03bfd82a47'
down_revision = '05b8081b7bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('shop_staff_id_fkey', 'shop', type_='foreignkey')
    op.drop_constraint('shop_owner_id_fkey', 'shop', type_='foreignkey')
    op.drop_column('shop', 'owner_id')
    op.drop_column('shop', 'staff_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('staff_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.add_column('shop', sa.Column('owner_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('shop_owner_id_fkey', 'shop', 'user', ['owner_id'], ['id'])
    op.create_foreign_key('shop_staff_id_fkey', 'shop', 'user', ['staff_id'], ['id'])
    # ### end Alembic commands ###
