"""fix raw table

Revision ID: e5df92585580
Revises: 71c0653084b5
Create Date: 2020-11-03 15:29:28.654443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e5df92585580'
down_revision = '71c0653084b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw', sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'raw', 'rawcategory', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw', type_='foreignkey')
    op.drop_column('raw', 'category_id')
    # ### end Alembic commands ###
