"""update raw model

Revision ID: f925c1b0638e
Revises: ebe1fcc85855
Create Date: 2020-12-07 17:37:03.527640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f925c1b0638e'
down_revision = 'ebe1fcc85855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw', 'quantity')
    op.drop_column('raw', 'cost')
    op.drop_column('raw', 'reserved')
    op.add_column('rawremainsdetail', sa.Column('reserved', sa.Float(), nullable=True, comment='Зарезервировано'))
    op.drop_column('rawremainsdetail', 'total')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rawremainsdetail', sa.Column('total', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Сумма'))
    op.drop_column('rawremainsdetail', 'reserved')
    op.add_column('raw', sa.Column('reserved', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Зарезервировано'))
    op.add_column('raw', sa.Column('cost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Стоимость остатка'))
    op.add_column('raw', sa.Column('quantity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Общий остаток'))
    # ### end Alembic commands ###
