"""add shop foreign key to product category

Revision ID: fdbef9b5796c
Revises: c72a2e169608
Create Date: 2020-10-18 14:45:21.041557

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fdbef9b5796c'
down_revision = 'c72a2e169608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productcategory', sa.Column('shop_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'productcategory', 'shop', ['shop_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productcategory', type_='foreignkey')
    op.drop_column('productcategory', 'shop_id')
    # ### end Alembic commands ###
