"""delete rows in InvoiceRecord model

Revision ID: fe0adf41a254
Revises: 994a10aa99a5
Create Date: 2020-11-30 17:24:33.728324

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fe0adf41a254'
down_revision = '994a10aa99a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoicerecord_category_id_fkey', 'invoicerecord', type_='foreignkey')
    op.drop_column('invoicerecord', 'total')
    op.drop_column('invoicerecord', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoicerecord', sa.Column('category_id', postgresql.UUID(), autoincrement=False, nullable=False, comment='Категория'))
    op.add_column('invoicerecord', sa.Column('total', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment='Сумма'))
    op.create_foreign_key('invoicerecord_category_id_fkey', 'invoicerecord', 'rawcategory', ['category_id'], ['id'])
    # ### end Alembic commands ###
